includes:
- configs/is2re/10k/base.yml

model:
  name: egnn
  in_features: 9
  out_features: 200
  hidden_features: 200
  hidden_layer: 7
  dim: 3
  update_pos: True

optim:
  batch_size: 4
  eval_batch_size: 4
  num_workers: 8
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 4
    - 8
    - 12
  warmup_epochs: 2
  warmup_factor: 0.2
  max_epochs: 20
