includes:
- configs/is2re/all/base.yml
#- configs/is2re/all/base_wpos.yml

model:
#  name: segnn
  name: segnn2
  in_features: 9
  out_features: 1
  hidden_features: 128
  N: 7
  dim: 3
  lmax_h: 2
  lmax_pos: 2
  update_pos: False
  recurrent: True

optim:
  batch_size: 3
  eval_batch_size: 3
  num_workers: 8
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 10
    - 14
    - 18
  warmup_epochs: 2
  warmup_factor: 0.2
  max_epochs: 20
